"""empty message

Revision ID: d5b4f39076a9
Revises: c1183e7f67f6
Create Date: 2019-09-10 20:34:42.833778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5b4f39076a9'
down_revision = 'c1183e7f67f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('meal')
    op.add_column('recipe', sa.Column('tag_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.create_foreign_key(None, 'recipe', 'tag', ['tag_id'], ['id'])
    op.drop_column('recipe', 'meal_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('meal_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.create_foreign_key(None, 'recipe', 'meal', ['meal_id'], ['id'])
    op.drop_column('recipe', 'tag_id')
    op.create_table('meal',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('category', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tag')
    # ### end Alembic commands ###
